title: Math
email: mail@joshchen.io
description: >-
  Math and type theory notes
baseurl: &baseurl "/math"
url: "https://joshchen.io/"
twitter_username: jaycech3n
github_username: jaycech3n

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null # disable math engine and let the client side use KaTeX for simple LaTeX

katex:
  macros:
    # "\\ExampleGlobalMacro": "\\LaTeX"
  delimiters:
    - {left: "$", right: "$", display: false}
    - {left: "\\(", right: "\\)", display: false}
    - {left: "\\[", right: "\\]", display: true}
    - {left: "\\begin{align}", right: "\\end{align}", display: true}

antex:
  url_path_prefix: *baseurl
  aliases: # disable most aliases and use server side AnTeX only for complex LaTeX
    display_math: false
    inline_math: false
    inline_macro: false

plugins:
  - jekyll-feed
  - jekyll-scholar

exclude:
  # non default values:
  - README.md
  - krater.png
  - bak
  # default values:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .nojekyll # tells GHP not to run Jekyll again on the build

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      katex:
        macros:
      antex:
        preamble:
      layout: "default"
      theorem-numbers: true

collections:
  notes:
    output: true
    permalink: :name

